name: End-to-end tests parallel
on: [push]
jobs:
  Teste-login:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          command: npm run login_teste
  Teste-Cadastro-Perfil:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          command: npm run cadastro_perfil_acesso_teste
  Teste-Cadastro-Usuário:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          command: npm run cadastro_usuario_teste
